~ "../html"
  ~ A Body Code Div Escape Head Html
  ~ H₄ LI Link Meta Title UL UiuaCode

&p Html {
  Head {
    Title "Advent of Code Solutions"
    ⬚∘Link [
      {"rel" "icon"}
      {"type" "image/x-icon"}
      {"href" "/root/favicon.ico"}
    ] {}
    ⬚∘Meta [{"charset" "UTF-8"}] {}
  }
  Body {
    ⬚∘Div [{"style" "white-space: pre"}] {
      UL ⍚(
        LI {⊃(H₄ $"Path: _"|UiuaCode Escape &fras)}
      )
      ▽⊸≡◇(≍".ua"↙₋₃)
      &fld "/home/bennet/uiua/aoc/2024/"
    }
  }
}
